import { OSType } from "../enums";
import { FileType, IDistribution } from "../interfaces";

export class Distributions{
    static readonly list:IDistribution[]=[
        {
            os:OSType.Windows,
            releases:[
                {
                    version:"1.0.0(latest)",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v1.0.0/LithiumGit-Setup-win-x64-1.0.0.exe",
                        }                        
                    ]
                },
                {
                    version:"0.5.3-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.5.3-alpha.1/LithiumGit-Setup-win-x64-0.5.3-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.5.2-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.5.2-alpha.1/LithiumGit-Setup-win-x64-0.5.2-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.5.1-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.5.1-alpha.1/LithiumGit-Setup-win-x64-0.5.1-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.5.0-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.5.1-alpha.1/LithiumGit-Setup-win-x64-0.5.1-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.4.4-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.4.4-alpha.1/LithiumGit-Setup-win-x64-0.4.4-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.4.3-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.4.3-alpha.1/LithiumGit-Setup-win-x64-0.4.3-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.4.2-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.4.2-alpha.1/LithiumGit-Setup-win-x64-0.4.2-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.4.1-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.4.1-alpha.1/LithiumGit-Setup-win-x64-0.4.1-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.3.2-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.3.2-alpha.1/LithiumGit-Setup-win-x64-0.3.2-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.3.1-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.3.1-alpha.1/LithiumGit-Setup-win-x64-0.3.1-alpha.1.exe",
                        }
                    ]
                },
                {
                    version:"0.3.0-alpha.1",
                    files:[
                        {
                            type:FileType.EXE,
                            url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v0.3.0-alpha.1/LithiumGit-Setup-win-x64-0.3.0-alpha.1.exe",
                        }
                    ]
                },
            ]
        },
        {
            os:OSType.Mac,
            releases:[{
                version:"1.0.0(latest)",
                files:[{
                    type:FileType.DMG,
                    url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v1.0.0/LithiumGit-Setup-mac-x64-1.0.0.dmg"
                }]
            }]
        },
        {
            os:OSType.Linux,
            releases:[{
                files:[
                    {
                        type:FileType.DEV,
                        url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v1.0.0/LithiumGit-Setup-linux-amd64-1.0.0.deb"
                    },
                    {
                        type:FileType.AppImage,
                        url:"https://github.com/TulshiDas39/LithiumGit/releases/download/v1.0.0/LithiumGit-Setup-linux-x86_64-1.0.0.AppImage"
                    },
                ],
                version:"1.0.0(latest)",
            }],
        }
    ];
}