import 'bootstrap/dist/css/bootstrap.min.css';
import "./styles/styles.scss";
import { EnumTheme, StorageUtils } from '../lib';
import { Footer } from './components/footer';


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme={StorageUtils.getTheme()}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
