import 'bootstrap/dist/css/bootstrap.min.css';
import "./styles/styles.scss";
import { EnumTheme } from '../lib';


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme={EnumTheme.Dark}>
      <body>
        {children}
      </body>
    </html>
  );
}
